# Optional: verify this daemon’s binary against a known SHA-256
self_integrity_path: "/usr/local/share/watchdogfs/self.sha256"

jobs:
  check_etc_passwd:
    watch_paths:
      - "/etc/passwd"
      - "/etc/group"
    ignore_patterns: []
    watcher:
      mode: "inotify"        # use inotify for immediate alerts
      poll_interval: 5       # (ignored in inotify mode, but kept for completeness)
      debounce_ms: 500       # debounce window in milliseconds
    alerts:
      use_syslog: true
      webhook_url: "https://alerts.example.com/notify"
      script_path: "/usr/local/bin/alert_handler.sh"
      payload_template: |
        {
          "changed_file": "{{path}}",
          "previous_checksum": "{{old}}",
          "current_checksum": "{{new}}",
          "severity": "critical"
        }

  check_var_www:
    watch_paths:
      - "/var/www/html"
    ignore_patterns:
      - "*.tmp"
      - "*.swp"
    watcher:
      mode: "poll"           # fall back to polling every interval
      poll_interval: 10      # check every 10 seconds
      debounce_ms: 1000      # ignore repeat‐events within 1 second
    alerts:
      use_syslog: false
      webhook_url: null       # no webhook for this job
      script_path: "/usr/local/bin/www_alert.sh"
      payload_template: |
        {
          "alert": "web content modified",
          "file": "{{path}}",
          "old_sum": "{{old}}",
          "new_sum": "{{new}}"
        }
